server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: spring-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

  main:
    allow-circular-references: true

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: "*"

